In [3]:
import numpy as np

In [2]:
import pandas as pd

In [11]:
df = pd.read_csv("titanic.csv")
df #whole data

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,892,0,3,"Kelly, Mr. James",male,34.5,0,0,330911,7.8292,NaN,Q
1,893,1,3,"Wilkes, Mrs. James (Ellen Needs)",female,47.0,1,0,363272,7.0000,NaN,S
2,894,0,2,"Myles, Mr. Thomas Francis",male,62.0,0,0,240276,9.6875,NaN,Q
3,895,0,3,"Wirz, Mr. Albert",male,27.0,0,0,315154,8.6625,NaN,S
4,896,1,3,"Hirvonen, Mrs. Alexander (Helga E Lindqvist)",female,22.0,1,1,3101298,12.2875,NaN,S
...,...,...,...,...,...,...,...,...,...,...,...,...
413,1305,0,3,"Spector, Mr. Woolf",male,NaN,0,0,A.5. 3236,8.0500,NaN,S
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C
415,1307,0,3,"Saether, Mr. Simon Sivertsen",male,38.5,0,0,SOTON/O.Q. 3101262,7.2500,NaN,S
416,1308,0,3,"Ware, Mr. Frederick",male,NaN,0,0,359309,8.0500,NaN,S
417,1309,0,3,"Peter, Master. Michael J",male,NaN,1,1,2668,22.3583,NaN,C

In [13]:
df.describe

<bound method NDFrame.describe of      PassengerId  Survived  Pclass  \
0            892         0       3
1            893         1       3
2            894         0       2
3            895         0       3
4            896         1       3
..           ...       ...     ...
413         1305         0       3
414         1306         1       1
415         1307         0       3
416         1308         0       3
417         1309         0       3

                                             Name     Sex   Age  SibSp  Parch  \
0                                Kelly, Mr. James    male  34.5      0      0
1                Wilkes, Mrs. James (Ellen Needs)  female  47.0      1      0
2                       Myles, Mr. Thomas Francis    male  62.0      0      0
3                                Wirz, Mr. Albert    male  27.0      0      0
4    Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1      1
..                                            ...     ...   ...    ...    ...
413                            Spector, Mr. Woolf    male   NaN      0      0
414                  Oliva y Ocana, Dona. Fermina  female  39.0      0      0
415                  Saether, Mr. Simon Sivertsen    male  38.5      0      0
416                           Ware, Mr. Frederick    male   NaN      0      0
417                      Peter, Master. Michael J    male   NaN      1      1

                 Ticket      Fare Cabin Embarked
0                330911    7.8292   NaN        Q
1                363272    7.0000   NaN        S
2                240276    9.6875   NaN        Q
3                315154    8.6625   NaN        S
4               3101298   12.2875   NaN        S
..                  ...       ...   ...      ...
413           A.5. 3236    8.0500   NaN        S
414            PC 17758  108.9000  C105        C
415  SOTON/O.Q. 3101262    7.2500   NaN        S
416              359309    8.0500   NaN        S
417                2668   22.3583   NaN        C

[418 rows x 12 columns]>

In [12]:
df.columns #only columns

Index(['PassengerId', 'Survived', 'Pclass', 'Name', 'Sex', 'Age', 'SibSp',
       'Parch', 'Ticket', 'Fare', 'Cabin', 'Embarked'],
      dtype='object')

In [16]:
#female passenger
female_passengers = df[df["Sex"]=="female"]
print(female_passengers)

     PassengerId  Survived  Pclass  \
1            893         1       3
4            896         1       3
6            898         1       3
8            900         1       3
12           904         1       1
..           ...       ...     ...
409         1301         1       3
410         1302         1       3
411         1303         1       1
412         1304         1       3
414         1306         1       1

                                                Name     Sex   Age  SibSp  \
1                   Wilkes, Mrs. James (Ellen Needs)  female  47.0      1
4       Hirvonen, Mrs. Alexander (Helga E Lindqvist)  female  22.0      1
6                               Connolly, Miss. Kate  female  30.0      0
8          Abrahim, Mrs. Joseph (Sophie Halaut Easu)  female  18.0      0
12     Snyder, Mrs. John Pillsbury (Nelle Stevenson)  female  23.0      1
..                                               ...     ...   ...    ...
409                        Peacock, Miss. Treasteall  female   3.0      1
410                           Naughton, Miss. Hannah  female   NaN      0
411  Minahan, Mrs. William Edward (Lillian E Thorpe)  female  37.0      1
412                   Henriksson, Miss. Jenny Lovisa  female  28.0      0
414                     Oliva y Ocana, Dona. Fermina  female  39.0      0

     Parch              Ticket      Fare Cabin Embarked
1        0              363272    7.0000   NaN        S
4        1             3101298   12.2875   NaN        S
6        0              330972    7.6292   NaN        Q
8        0                2657    7.2292   NaN        C
12       0               21228   82.2667   B45        S
..     ...                 ...       ...   ...      ...
409      1  SOTON/O.Q. 3101315   13.7750   NaN        S
410      0              365237    7.7500   NaN        Q
411      0               19928   90.0000   C78        Q
412      0              347086    7.7750   NaN        S
414      0            PC 17758  108.9000  C105        C

[152 rows x 12 columns]

In [17]:
#fare greater than 30
df[df["Fare"]>30]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
12,904,1,1,"Snyder, Mrs. John Pillsbury (Nelle Stevenson)",female,23.0,1,0,21228,82.2667,B45,S
14,906,1,1,"Chaffee, Mrs. Herbert Fuller (Carrie Constance...",female,47.0,1,0,W.E.P. 5734,61.1750,E31,S
20,912,0,1,"Rothschild, Mr. Martin",male,55.0,1,0,PC 17603,59.4000,NaN,C
22,914,1,1,"Flegenheim, Mrs. Alfred (Antoinette)",female,NaN,0,0,PC 17598,31.6833,NaN,S
23,915,0,1,"Williams, Mr. Richard Norris II",male,21.0,0,1,PC 17597,61.3792,NaN,C
...,...,...,...,...,...,...,...,...,...,...,...,...
402,1294,1,1,"Gibson, Miss. Dorothy Winifred",female,22.0,0,1,112378,59.4000,NaN,C
403,1295,0,1,"Carrau, Mr. Jose Pedro",male,17.0,0,0,113059,47.1000,NaN,S
407,1299,0,1,"Widener, Mr. George Dunton",male,50.0,1,1,113503,211.5000,C80,C
411,1303,1,1,"Minahan, Mrs. William Edward (Lillian E Thorpe)",female,37.0,1,0,19928,90.0000,C78,Q
414,1306,1,1,"Oliva y Ocana, Dona. Fermina",female,39.0,0,0,PC 17758,108.9000,C105,C

In [ ]:
#group by pclass then find: survival rate, avg. fare, avg. age

In [19]:
df.groupby("Pclass").size() #number of passengers in each Pclass

Pclass
1    107
2     93
3    218
dtype: int64

In [20]:
df.groupby("Pclass")["Survived"].mean() #survival rate in each pclass

Pclass
1    0.467290
2    0.322581
3    0.330275
Name: Survived, dtype: float64

In [21]:
df.groupby("Pclass")["Fare"].mean() #average fare in each pclass

Pclass
1    94.280297
2    22.202104
3    12.459678
Name: Fare, dtype: float64

In [22]:
df.groupby("Pclass")["Age"].mean() #average age in each pclass

Pclass
1    40.918367
2    28.777500
3    24.027945
Name: Age, dtype: float64

In [25]:
df["Survived"].value_counts() # 0 means not survived, 1 means survived

Survived
0    266
1    152
Name: count, dtype: int64

In [26]:
df.groupby("Sex")["Survived"].mean() #survived mean

Sex
female    1.0
male      0.0
Name: Survived, dtype: float64